name: Daily Digest (scrape & publish)

on:
  schedule:
    - cron: '15 10 * * *'      # runs daily at 15:45 IST (10:15 UTC)
  workflow_dispatch:           # allows manual runs from Actions UI

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run daily digest script
        run: python main.py

      - name: Commit and push outputs if changed
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add data || true

          if ! git diff --staged --quiet; then
            git commit -m "Daily Digest: update data and report — $(date --utc +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
