name: Daily Digest (scrape & publish)

on:
  schedule:
    - cron: '0 10 * * *'      # daily at 15:30 IST (10:00 UTC)
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install apt dependencies and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          # Add Google Chrome repo and key
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run daily digest script
        # change to 'python src/main.py' if needed
        run: python main.py

      - name: Commit and push outputs if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          # stage output dir (no-op if missing)
          git add data || true

          # If there are staged changes, commit & push. Otherwise print message.
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Daily Digest: update data and report — $(date --utc +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi

